name: "Required Approvals"
description: "Checks if the required codeowners have approved a PR and requires a minimum number of approvals"
branding:
  icon: "check-square"
  color: "green"
inputs:
  token:
    description: "GitHub token"
    required: true
  read_org_scoped_token:
    description: "GitHub token with read:org scope"
    required: true
  org_name:
    description: "Organization name"
    required: true
  min_approvals:
    description: "Minimum number of approvals"
    required: true
  pr_number:
    description: "Pull request number, mutually exclusive with branch, will check approvals on this PR if supplied. If not supplied, will check approvals on the PR that triggered the workflow. If both pr_number and branch are supplied it will default to the latest pr on the branch."
    required: false
  branch:
    description: "Branch name, mutually exclusive with pr_number, will look for prs from this branch if supplied, and select the newest one if there are multiple. If not supplied, will check approvals on the PR that triggered the workflow.  If both pr_number and branch are supplied it will default to the latest pr on the branch."
    required: false
  require_all_approvals_latest_commit:
    description: "Require all approvals to be on the latest commit of the PR, ignore approvals on previous commits."
    required: false
    default: "true"
  limit_org_teams_to_codeowners_file:
    description: "Enable to limit a user's team membership check to only those specified in the CODEOWNERS file. This overrides the default behavior of checking all teams in the organization 'org_name'. Consider enabling for environments with a large number of teams to reduce execution time."
    required: false
    default: "false"
  approval_mode:
    description: 'Determines the approval requirement for codeowners. If set to "ALL", all codeowners must approve. If set to "ANY", at least one approval from a codeowner is sufficient. If not provided, the default is "ALL".'
    required: false
    default: "ALL"
outputs:
  teams:
    description: "Teams that still need to provide reviews"

runs:
  using: "node20"
  main: "dist/index.js"
